(data-preprocessing)=
# Data Preprocessing

### utils.<br>**check_test_sites**

```python
check_test_sites(train_data, test_data)
```

&nbsp;&nbsp;&nbsp;&nbsp;Validates that your testing data 'site' column is a subset of the training data 'site' column. Displays extra sites and their sample distributions.

&nbsp;&nbsp;&nbsp;&nbsp;<span style="background-color: #f5f5f5; padding: 4px 8px; display: inline-block; width: 90%;">**Parameters:**</span>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**train_data** : ***pandas.DataFrame*** <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DataFrame containing the training data with 'site' column

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**test_data** : ***pandas.DataFrame*** <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DataFrame containing the test data with 'site' column

&nbsp;&nbsp;&nbsp;&nbsp;<span style="background-color: #f5f5f5; padding: 4px 8px; display: inline-block; width: 90%;">**Returns:**</span>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**None** : ***None*** <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Prints site distribution information and recommendations

<br>

**Examples:**

In [3]:
from normgamlss.utils import (
    add_extra_site_data,
    check_test_sites,
)

check_test_sites(train_data, test_data)

Number of unique sites in the training set: 5
Number of unique sites in the test set: 8
Test sites not present in the training set: ['HLMEG', 'KEMUB', 'ZSCPY']
Number of extra sites: 3

    site  Length  Healthy                             Morbidities
0  HLMEG      69       58  Len: 11, ['MDD', 'Schizo', 'Dementia']
1  KEMUB      58       47  Len: 11, ['Schizo', 'MDD', 'Dementia']
2  ZSCPY      59       51   Len: 8, ['Schizo', 'Dementia', 'MDD']

Suggestion: Use 20% of 'None' samples from extra sites in the training data.
This can be done by calling the 'add_extra_site_data' function.

### utils.<br>**add_extra_site_data**

```python
add_extra_site_data(train_data, test_data, fraction=0.2)
```

&nbsp;&nbsp;&nbsp;&nbsp;Adds a fraction of healthy ('None') samples from extra sites in the test dataset to the training dataset to improve model performance on new sites.

&nbsp;&nbsp;&nbsp;&nbsp;<span style="background-color: #f5f5f5; padding: 4px 8px; display: inline-block; width: 90%;">**Parameters:**</span>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**train_data** : ***pandas.DataFrame*** <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DataFrame containing the training data

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**test_data** : ***pandas.DataFrame*** <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DataFrame containing the test data  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**fraction** : ***float***, *default=0.2* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fraction of 'None' samples to add from extra sites

&nbsp;&nbsp;&nbsp;&nbsp;<span style="background-color: #f5f5f5; padding: 4px 8px; display: inline-block; width: 90%;">**Returns:**</span>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**train_data** : ***pandas.DataFrame*** <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Updated training dataset with added samples from extra sites

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**test_data** : ***pandas.DataFrame*** <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Updated test dataset with removed samples added to training

<br>

**Examples:**

In [4]:
train_data1, test_data1 = add_extra_site_data(train_data, test_data, fraction=0.2)

Extra sites found in the test set: ['HLMEG', 'KEMUB', 'ZSCPY']

In [5]:
# Sanity check: confirm the sites in test data are a superset of the sites in train data
print(set(train_data1.site.unique()).difference(set(test_data1.site.unique())))
print("If above set is empty means we successfully added extra site data to train data")

set()
If above set is empty means we successfully added extra site data to train data

In [6]:
train_data1.head()

,site,sex,age,feature_volume1,feature_volume2,feature_volume3,feature_volume4,feature_volume5,y_thickness1,y_thickness2,y_thickness3,y_thickness4
0,HJDXM,0,56,848.209032,1019.328233,942.341904,844.454859,1171.438753,21.277471,23.285272,30.851458,24.390216
1,BCCLF,0,69,1092.409469,851.195283,833.567814,1059.242014,1095.497404,23.369578,21.380807,31.456619,23.368378
2,ESZYC,1,46,877.039611,1152.854246,933.385037,1150.047218,922.507155,22.482468,25.267274,34.556324,23.208468
3,BCCLF,0,32,846.112808,957.379139,1071.016378,1116.208204,906.032514,22.553167,23.751988,36.149900,23.229095
4,HSREL,0,60,968.705064,1131.147350,828.844437,856.443038,1078.476980,22.484007,24.163945,29.541937,23.391176

### utils.<br>**remove_special_characters**

```python
remove_special_characters(dataframes)
```

&nbsp;&nbsp;&nbsp;&nbsp;R library might give errors if your columns have special characters in their names, such as hyphens ("-"), ampersands ("&"), or spaces. This function replaces these special characters with underscores ("_").

&nbsp;&nbsp;&nbsp;&nbsp;<span style="background-color: #f5f5f5; padding: 4px 8px; display: inline-block; width: 90%;">**Parameters:**</span>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**dataframes** : ***list of pandas.DataFrame*** <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;List of DataFrames to process

&nbsp;&nbsp;&nbsp;&nbsp;<span style="background-color: #f5f5f5; padding: 4px 8px; display: inline-block; width: 90%;">**Returns:**</span>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**modified_dfs** : ***list of pandas.DataFrame*** <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;List of DataFrames with modified column names

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**name_maps** : ***list of dict*** <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;List of dictionaries mapping new column names to original names

<br>

**Examples:**


```python
# For a single dataframe
[modified_df], [name_map] = remove_special_characters([df])
original_name = name_map['column_1_2']  # Returns 'column-1 & 2'

# For multiple dataframes
[modified_df1, modified_df2], [name_map1, name_map2] = remove_special_characters([df1, df2])
```