(model-predictions)=
# Model Predictions

### gamlss_main.Gamlss.<br>**predict_all**

```python
predict_all(test_data, train_data, transform=True, verbose=False)
```

&nbsp;&nbsp;&nbsp;&nbsp;Generates predictions from the fitted GAMLSS model. When transform=True, predictions are on the response scale; when False, on the link scale.

&nbsp;&nbsp;&nbsp;&nbsp;<span style="background-color: #f5f5f5; padding: 4px 8px; display: inline-block; width: 90%;">**Parameters:**</span>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**test_data** : ***pandas.DataFrame*** <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DataFrame containing the test data

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**train_data** : ***pandas.DataFrame*** or ***None*** <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DataFrame containing the training data. None for a slim model (see *Sharing a model without the training data* in Saving and Loading Models)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**transform** : ***bool***, *default=True* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Whether to apply transformations (response vs link scale)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**verbose** : ***bool***, *default=False* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Whether to print model summary and transformation details

&nbsp;&nbsp;&nbsp;&nbsp;<span style="background-color: #f5f5f5; padding: 4px 8px; display: inline-block; width: 90%;">**Returns:**</span>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**predictions** : ***pandas.DataFrame*** <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DataFrame with predicted values for available parameters (mu, sigma, nu, tau)

<br>


**Examples:**

In [13]:
# Testing on the test dataset
df_test = test_data1.loc[:, columns]
predictions = gamlss_model.predict_all(df_test,df_train, transform=True, verbose=False)
predictions

       mu_pred  sigma_pred    nu_pred   tau_pred
1    24.162162   14.978377  10.998055  10.823626
2    24.083428   14.979424  10.998055  10.823626
3    22.665159   15.008508  10.998055  10.823626
4    22.778040   15.005153  10.998055  10.823626
5    22.540969   15.015308  10.998055  10.823626
..         ...         ...        ...        ...
466  23.706228   14.994779  10.998055  10.823626
467  25.134436   14.969788  10.998055  10.823626
468  23.236998   14.993781  10.998055  10.823626
469  23.056083   15.015309  10.998055  10.823626
470  23.351317   15.005154  10.998055  10.823626

[470 rows x 4 columns]

In [14]:
predictions.describe()

          mu_pred  sigma_pred       nu_pred      tau_pred
count  470.000000  470.000000  4.700000e+02  4.700000e+02
mean    23.673564   14.994198  1.099806e+01  1.082363e+01
std      0.858797    0.017331  4.623449e-14  5.334749e-14
min     22.520930   14.965388  1.099806e+01  1.082363e+01
25%     22.974408   14.978375  1.099806e+01  1.082363e+01
50%     23.508932   14.994780  1.099806e+01  1.082363e+01
75%     24.410390   15.010102  1.099806e+01  1.082363e+01
max     25.376388   15.021446  1.099806e+01  1.082363e+01