(model-predictions)=
# Model Predictions

### gamlss_main.Gamlss.<br>**predict_all**

```python
predict_all(test_data, train_data, transform=True, verbose=False)
```

&nbsp;&nbsp;&nbsp;&nbsp;Generates predictions from the fitted GAMLSS model. When transform=True, predictions are on the response scale; when False, on the link scale.

&nbsp;&nbsp;&nbsp;&nbsp;<span style="background-color: #f5f5f5; padding: 4px 8px; display: inline-block; width: 90%;">**Parameters:**</span>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**test_data** : ***pandas.DataFrame*** <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DataFrame containing the test data

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**train_data** : ***pandas.DataFrame*** <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DataFrame containing the training data

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**transform** : ***bool***, *default=True* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Whether to apply transformations (response vs link scale)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**verbose** : ***bool***, *default=False* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Whether to print model summary and transformation details

&nbsp;&nbsp;&nbsp;&nbsp;<span style="background-color: #f5f5f5; padding: 4px 8px; display: inline-block; width: 90%;">**Returns:**</span>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**predictions** : ***pandas.DataFrame*** <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DataFrame with predicted values for available parameters (mu, sigma, nu, tau)

<br>


**Examples:**

In [13]:
# Testing on the test dataset
df_test = test_data1.loc[:, columns]
predictions = gamlss_model.predict_all(df_test,df_train, transform=True, verbose=False)
predictions

R[write to console]: In grSoftVersion() :
R[write to console]:  unable to load shared object '/usr/lib/R/modules//R_X11.so':
  libicuuc.so.73: cannot open shared object file: No such file or directory

R[write to console]: In cairoVersion() :
R[write to console]:  unable to load shared object '/usr/lib/R/library/grDevices/libs//cairo.so':
  libicuuc.so.73: cannot open shared object file: No such file or directory

R[write to console]: In (function (filename = "Rplot%03d.png", width = 480, height = 480,  :
R[write to console]:  failed to load cairo DLL

       mu_pred  sigma_pred   nu_pred  tau_pred
1    24.147695    2.733589  2.125571  2.090123
2    24.067658    2.733915  2.125571  2.090123
3    22.656329    2.741308  2.125571  2.090123
4    22.772542    2.740789  2.125571  2.090123
5    22.526281    2.741867  2.125571  2.090123
..         ...         ...       ...       ...
466  23.708506    2.738382  2.125571  2.090123
467  25.125914    2.730802  2.125571  2.090123
468  23.214748    2.738112  2.125571  2.090123
469  23.072959    2.741867  2.125571  2.090123
470  23.362624    2.740789  2.125571  2.090123

[470 rows x 4 columns]

In [14]:
predictions.describe()

          mu_pred  sigma_pred       nu_pred      tau_pred
count  470.000000  470.000000  4.700000e+02  4.700000e+02
mean    23.669538    2.737359  2.125571e+00  2.090123e+00
std      0.858320    0.004232  4.445624e-15  1.956075e-14
min     22.518656    2.729325  2.125571e+00  2.090123e+00
25%     22.965473    2.733588  2.125571e+00  2.090123e+00
50%     23.508743    2.738382  2.125571e+00  2.090123e+00
75%     24.401521    2.741500  2.125571e+00  2.090123e+00
max     25.379274    2.741920  2.125571e+00  2.090123e+00